### ISSUE TITLE
Support hotplugin for zdb disks

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/0-core#12]
*Issue migrated from [https://api.github.com/repos/zero-os/0-core/issues/650](), opened by @grimpy*

Currenty we pass zdb disks via qemu args in libvirt with this approach its not possible to laverage libvirts attach/detach device support.

We have 2options to solve this.
1: we talk to qemu directly to instruct a device removale/attachement
2: we implement zdb support inside libvirt

**Comment by rkhamis** [comment]
*commented by @muhamadazmy
We waiting for the support of libvirt.*

**Comment by rkhamis** [comment]
*commented by @muhamadazmy
@maxux any update on the libvirt integration for zdb ?*

**Comment by rkhamis** [comment]
*commented by @maxux
Nothing changed, no update for now*

**Comment by rkhamis** [comment]
*commented by @zaibon
@muhamadazmy is this something you can work on yourself ?*

**Comment by despiegk** [comment]
we are not going to do in GIG
