### ISSUE TITLE
port forward not re-created after container restart

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-core#125]
I had a situation where I had some 0-db container that I needed to upgrade.
So I stop/started these container to get the newest version, but for some reason most of my 0-db were not reachable anymore after that.

After investigation it turns out that the problem was the port forward to the container, it was not created at all.
Here is a snippet of the nft table of one of the node.

```
chain pre {
    type nat hook prerouting priority 0; policy accept;
    ip daddr @host iifname "zt*" tcp dport 6600 dnat to 172.18.0.29:6600
    ip daddr @host tcp dport 1025 dnat to 172.18.0.30:9900
    ip daddr @host tcp dport 1029 dnat to 172.18.0.41:9900
    ip daddr @host tcp dport 1036 dnat to 172.18.0.42:9900
    ip daddr @host tcp dport 1024 dnat to 172.18.0.43:9900
    ip daddr @host tcp dport 1028 dnat to 172.18.0.44:9900
    ip daddr @host tcp dport 1032 dnat to 172.18.0.46:9900
    ip daddr @host tcp dport 1041 dnat to 172.18.0.47:9900
    ip daddr @host tcp dport 1030 dnat to 172.18.0.48:9900
  }
```
And one of the 0-db container, we see that the container has some port forward configure that are not present in nft table.
```
and my container 
In [83]: cont.ports
Out[83]: {'1038': 9900}

In [84]: cont.default_ip()
Out[84]: IPNetwork('172.18.0.36/16')
```

**Comment by muhamadazmy** [comment]
I am already working on a fix on development. Will have to cherrypick on 1.5.0, hopefully by Sunday.

**Comment by zaibon** [comment]
So you think this could be solve by the work you are already doing around this topic? That's good

**Comment by muhamadazmy** [comment]
@zaibon  Can we have a confirmation that this is no longer an issue ?

**Comment by zaibon** [comment]
Just finished to do some testing with the fixes we made about this, and it seems everything works as expected. I close the issue
