### ISSUE TITLE
Container creation fails on development image

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/0-core#162]
Creating a container on the latest development branch fails 

https://github.com/threefoldtech/zos/issues/93#issuecomment-498299987

**Comment by robvanmieghem** [comment]
Issue where the problem was discovered and steps to reproduce:

https://github.com/threefoldtech/zos/issues/93
https://github.com/threefoldtech/zos/issues/93#issuecomment-498299987

**Comment by muhamadazmy** [comment]
It seems it was a regression bug in 0-fs itself, a print statement was remove that was used as a signal to core0 that the mount is fully ready and the system can proceed with starting the container.

The fix is here
https://github.com/threefoldtech/0-fs/commit/c503ac97516425f14b40afe1a6867cb14b6f1ceb

**Comment by muhamadazmy** [comment]
@robvanmieghem can u download the latest image (when it's done building) and confirm that this fixed it.
