### ISSUE TITLE
Connectivity check: tcp open instead of http get

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/0-core#21]
Current, we check internet connectivity of the node by trying to HTTP GET of www.google.com, and we do that every 5 seconds. This has many issues as follows:

- Too much data wasted, consumes a lot of bandwidth, even if the page is small, doing this forever will eventually eat up downlink quota 
- Apparently golang stdlib does not cache dns lookup records, it means for each http.Get call we make, there is also a dnslookup request is made to the configured dns, doing this for 5 seconds per node, then for as many nodes as u have in your farm, this adds up to many lookup requests that exhausts the dns server.

Suggestions:
- We do a tcp open only, once connection is established we close the socket. No actual data is transmitted over the wire (except for the initial tcp handshake packets)
- Find a dns cache library to be used with the standard http library (https://github.com/rs/dnscache) looks promissing.
- We do the check every 5 seconds on boot, until a connection is established, then we backup the check for every 10 minutes instead.

**Comment by zaibon** [comment]
after upgrading all the node the farm in belgium, the dns queries dropped to 0. So the fix in https://github.com/threefoldtech/0-core/commit/9af2cecd2073a6a3f5906da974d898eff0b694fa seems to do his job
