### ISSUE TITLE
Performance testing on ZOS 

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/0-core#33]
- Run fio on variable number of vms which have 0-db as a backend. 
- Use bancadati and create one vdisk per one VM.
- Make sure all results are collected using rtinfo.

**Comment by rkhamis** [comment]
Test should:
 - Deploy 100 VMs
 - each VM spawns 2 S3s
 - S3 to deploy 200 ZDB namespaces

please notice you can use the s3 templates for deployment

See: https://trello.com/c/1yLLYIDJ/4-basic-performance-tests-v10

**Comment by FastGeert** [comment]
Test should:
- deploy 50 dm vm's
- in each dm vm, create 2 S3 services
- that results in 100 gateways + 100 vms running S3

They make use of the ZDB's that are available on all physical nodes in the dc

**Comment by ramezsaeed** [comment]
moved to
https://github.com/threefoldtech/home/issues/17
