### ISSUE TITLE
Rebooting VM from ZOS client is failed

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/0-core#35]
- create VM using flist = https://hub.grid.tf/tf-bootable/ubuntu:latest.flist
- open vnc port (5900) 
- connect to VM using vnc 
- (reboot or reset) the VM using zos client 
actual result:
- after (rebooting or reseting) the VM, it has been freezed
- after rebooting the VM several times, it has been destroyed

**Comment by Dinaamagdy** [comment]
the vm after reset stuck like that 
![screenshot from 2018-10-01 15-33-27](https://user-images.githubusercontent.com/24386802/46291735-878d9c00-c58f-11e8-92b8-592153e00c5f.png)

**Comment by john-kheir** [comment]
I checked kvm reboot and reset actions today .. And after doing reset and reboot, nothing happens.. the vm is just working normally.
