### ISSUE TITLE
support for zero-os VM to reach host network of the host

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-core#42]
In order to be able to implement the architecture defined here: ![https://docs.google.com/drawings/d/e/2PACX-1vRVhDVoxjTEun-V0m0u2ioAxMbxTP8fvpXWCS-Hwoz-dWvlDEWOuudbVQts3xkBZwx8InHiZ_E2YviD/pub?w=960&h=866](https://docs.google.com/drawings/d/e/2PACX-1vRVhDVoxjTEun-V0m0u2ioAxMbxTP8fvpXWCS-Hwoz-dWvlDEWOuudbVQts3xkBZwx8InHiZ_E2YviD/pub?w=960&h=866)

In this picture the containers in the VM needs to be able to access the zerodb that runs in container in the host.  I did some testing and it seems that at the moment it's not possible. @muhamadazmy is suspecting something could go wrong because both the host and the VM use the same network for the containers.

**Comment by zaibon** [comment]
For any detail about the setup, zos version, containers involved, check how s3 template does things : https://github.com/threefoldtech/0-templates/blob/development/templates/s3/s3.py

**Comment by Pishoy** [comment]
@zaibon please verify which scenario should be followed for verification : 

- first  scenario
1- create a zerodb container on host like a zdb container - zdbOne listen on port 9900
2- create a Zos VM on host and on it create a Ubuntu container - ubuntu-continer
3 check that  ubuntu-continer can reach zdbOne though 9900

- second scenario 
1- create s3 template against a farm with only one node up
2 - check s3 works properly, s3 should create the vm and zerodb container

**Comment by zaibon** [comment]
for this issue scenario 1 is enough

**Comment by Pishoy** [comment]
closing it as this has been verified before
