### ISSUE TITLE
Creating container with multiple port forward only creates one

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-core#49]
I've a bunch of containers that have multiple port forwards:
```
{'enp3s0f0:9900': 9900, 'zt*:9900': 9900}
{'enp3s0f0:9901': 9900, 'zt*:9901': 9900}
{'enp3s0f0:9902': 9900, 'zt*:9902': 9900}
{'enp3s0f0:9903': 9900, 'zt*:9903': 9900}
{'enp3s0f0:9904': 9900, 'zt*:9904': 9900}
{'enp3s0f0:9905': 9900, 'zt*:9905': 9900}
```
But when I look at the nft config generated for this:
```
type nat hook prerouting priority 0; policy accept;
iif "core0" mark set 0x00000001
iif "kvm0" mark set 0x00000001
iifname "zt*" tcp dport 6600 dnat to 172.18.0.27:6600
iifname "enp3s0f0" tcp dport 9900 dnat to 172.18.0.29:9900
iifname "zt*" tcp dport 9901 dnat to 172.18.0.30:9900
iifname "enp3s0f0" tcp dport 9902 dnat to 172.18.0.31:9900
iifname "zt*" tcp dport 9903 dnat to 172.18.0.32:9900
iifname "zt*" tcp dport 9904 dnat to 172.18.0.33:9900
iifname "zt*" tcp dport 9905 dnat to 172.18.0.34:9900
```

so it seems that only one of the two port forward have been created each time

**Comment by zaibon** [comment]
Seems the problems comes from https://github.com/threefoldtech/0-core/blob/4504a0260cc4fd5f7946de31814fb37b52d1a89e/apps/core0/helper/socat/socat.go#L96-L100

Since we keep a map in memory to know if a port is already used, but we only use the port number in the map not the interface:port, so we can always only have one port forward per source port.

**Comment by muhamadazmy** [comment]
There is no `clean` way to implement this without getting conflicting rules, and it was safer (and still is) is to hold the port exclusively for a port forward rule.

But we changed this so the container creation fails if u provided a port that is already in use.

**Comment by zaibon** [comment]
> But we changed this so the container creation fails if u provided a port that is already in use.

Should be good enough for now
