### ISSUE TITLE
add a primitives to ask for a free port

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-core#51]
In the 0-OS SAL we have a method to find a free port on a node. We usually use this when deploying workloads that needs to be exposed using a port forward: https://github.com/threefoldtech/jumpscale_lib/blob/2b368d2328a63d04ab126fec36ca307bd0ebebba/JumpscaleLib/sal_zos/node/Node.py#L241-L274

The problem with this approach is if 2 or more client call this method at the same time, they can both receive the same port as a response. Which will lead to one of the client to fail to create it's port forward cause it will already be take, while he just ask for a free port.

To solve this I think finding a free port should be a 0-OS primitive. Maybe something like a check and reserve port thingy. 
- a client ask for a free port to 0-OS
- 0-OS look what port if free, and remember that someone ask to use it
- the client the deploys his workload and use the port that he got from 0-OS
- 0-OS see that we ask a port forward for that port, it can remove it from the reserved list since it's now actually used

This should allow to have concurrent client asking for free port and make sure to always give them a valid port.

We should also maybe consider to cleanup the reserved port list after  while if someone ask for it and never actually used it.

**Comment by muhamadazmy** [comment]
@zaibon we can do this *decently* for port forwards only. But i guess this is the only use case we need, since it's not usually normal to start service on the host directly.

The free port reserve would still take care of the `listening` ports as well, so it doesn't mask a service that runs locally (for example redis port, or ssh)

**Comment by zaibon** [comment]
> @zaibon we can do this decently for port forwards only. But i guess this is the only use case we need, since it's not usually normal to start service on the host directly.

Indeed

> The free port reserve would still take care of the listening ports as well, so it doesn't mask a service that runs locally (for example redis port, or ssh)

perfect <3

**Comment by hossnys** [comment]
verified
branch : development 
lib : [eeb3c4a](https://github.com/threefoldtech/jumpscale_lib/commit/eeb3c4ab1e44a50b5ad56a3190b73028938bab4d)
prefab: [1574a75](https://github.com/threefoldtech/jumpscale_prefab/commit/1574a75cd680301e82360a91e97c93a154f5405e)
core: [f182ac3](https://github.com/threefoldtech/jumpscale_core/commit/f182ac37b4a284361615fb5372389967b82af1fa)
