### ISSUE TITLE
FR: support for multiple rtinfo clients

### ISSUE THREAD

**Issue by chrisvdg** [threefoldtech/0-core#60]
I've noticed that a zos node can only connect to one rtinfod server, would be nice to support pushing to multiple.

And maybe add a `list` method in the zos client so that we can see to which rtinfod's it's already pushing.

**Comment by zaibon** [comment]
Both already supported, check the api: https://github.com/threefoldtech/jumpscale_lib/blob/development/JumpscaleLib/clients/zero_os_protocol/RTInfoManager.py
