### ISSUE TITLE
FR: rtinfo is not persistent after reboot

### ISSUE THREAD

**Issue by chrisvdg** [threefoldtech/0-core#62]
I don't get any data anymore on the dashboard after a node has rebooted, would be nice if it was persistent.

**Comment by zaibon** [comment]
nothing is persistent on zero-os, the OS is stateless by design. If you need to persist state, you need a 0robot service for it

**Comment by chrisvdg** [comment]
Created an issue in 0-templates (https://github.com/threefoldtech/0-templates/issues/128)
Will try to write it myself
