### ISSUE TITLE
modify flist creation primitive to accept a hub URL to upload the generated flist automatically

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-core#80]

**Comment by maxux** [comment]
Gateway (to allows uploading on the hub publicly) is coming.

**Comment by muhamadazmy** [comment]
@zaibon this is merged, right? should be closed

**Comment by maxux** [comment]
The current implementation accept token argument but not a custom hub url, this can be added to make this issue fully resolved

**Comment by zaibon** [comment]
fixed in #81
