### ISSUE TITLE
Frozen zero-os node

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/0-core#85]
This morning one of the nodes I'm running suddenly froze (or seemed to have frozen).

Symptoms: 
- Containers on the node were no longer running (or at least no longer accessible)
- Zero robot no longer accessible
- Node itself was no longer accessible
- Attaching monitor to the node gave no output
- Attaching keyboard was unresponsive (e.g. unable to toggle numlock)

Version: master @Revision: 0a1352ebfa51bf40c9105656de97ed224af72bf2

**Comment by muhamadazmy** [comment]
How often this issue is reproducable. Can we reproduce by following certain steps ? 

Also when u reboot the nood, can u check the last boot logs and or crash logs if available.

**Comment by LeeSmet** [comment]
Issue happened twice last week, though we are not sure exactly what caused it. It happened on the node running our main explorers, so this node did have slightly more traffic than the others (though traffic throughput should still be low).

After node reboot I checked the log dir but none of the logs show anything special, all seems fine untill the node hangs.

**Comment by LeeSmet** [comment]
Happened again saturday morning. Node rebooted with VGA attached on kernel logs screen for now

**Comment by delandtj** [comment]
Happy new year Azmy! But this thing is scary, so can we try to get our heads together and try to imagine as for __why__ that could happen ?

**Comment by zaibon** [comment]
this really looks like hardware issue to me. Can we install another OS on this node and run the same workload see how it behaves ?

**Comment by LeeSmet** [comment]
memtest just passed a full test suite without errors (4/4 passes 0 errors).
Going to install manjaro on it I guess, still have an usb with that lying around

**Comment by LeeSmet** [comment]
For now the node is running an (up to date) manjaro linux with the same workload, as described in https://github.com/threefoldfoundation/tfchain/issues/249

**Comment by LeeSmet** [comment]
As it turns out, this seems to be a hardware issue
