### ISSUE TITLE
Can't create vm inside a zos-vm

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/0-core#96]
We need to enable `enable-kvm` flag for zos-vm to be able to create vms on it.

**Comment by zaibon** [comment]
I don't think we want to do VM inside VM anyhow. Where is this requirement coming from ?

**Comment by muhamadazmy** [comment]
This is how they run the tests. To avoid missing up the host they create a zos vm, then run the tests on there, so they need to be able to start more vms on top of this.

**Comment by delandtj** [comment]
which is a nice idea, then we can do destructive testing on production environments
but for that we'll need other vm XML templates so we expose emulated nics ans scsi controller __in__ the VM

**Comment by john-kheir** [comment]
This ticket is done and it is working now.
